services:

  postgres:
    image: postgres:17
    container_name: sentinelsoc-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: sentinelsoc
      POSTGRES_USER: sentinelsoc
      POSTGRES_PASSWORD: sentinelsoc_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: